apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    name: legallogin
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30000
