# Default values for sample-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: registry.hub.docker.com/hemantmaurya344/sample
  pullPolicy: IfNotPresent
  tag: "v1"

